// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9nqyOghWED9P4fZmCACUMSue_61WWwTI',
    appId: '1:668250306082:web:00bc8d291bc17e8a9dfc7b',
    messagingSenderId: '668250306082',
    projectId: 'okhealth-b8d73',
    authDomain: 'okhealth-b8d73.firebaseapp.com',
    databaseURL: 'https://okhealth-b8d73-default-rtdb.firebaseio.com',
    storageBucket: 'okhealth-b8d73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UVAOtfIYuO6CpByui13WSQRm0TRmne4',
    appId: '1:668250306082:android:5c347650d267e6079dfc7b',
    messagingSenderId: '668250306082',
    projectId: 'okhealth-b8d73',
    databaseURL: 'https://okhealth-b8d73-default-rtdb.firebaseio.com',
    storageBucket: 'okhealth-b8d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJH9-sWnGL6EvaewS5Z5WQ4FDcl8YSVZw',
    appId: '1:668250306082:ios:6efc64b24f9e386e9dfc7b',
    messagingSenderId: '668250306082',
    projectId: 'okhealth-b8d73',
    databaseURL: 'https://okhealth-b8d73-default-rtdb.firebaseio.com',
    storageBucket: 'okhealth-b8d73.firebasestorage.app',
    iosBundleId: 'com.example.healthMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJH9-sWnGL6EvaewS5Z5WQ4FDcl8YSVZw',
    appId: '1:668250306082:ios:6efc64b24f9e386e9dfc7b',
    messagingSenderId: '668250306082',
    projectId: 'okhealth-b8d73',
    databaseURL: 'https://okhealth-b8d73-default-rtdb.firebaseio.com',
    storageBucket: 'okhealth-b8d73.firebasestorage.app',
    iosBundleId: 'com.example.healthMonitorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9nqyOghWED9P4fZmCACUMSue_61WWwTI',
    appId: '1:668250306082:web:9324ac0126b3655e9dfc7b',
    messagingSenderId: '668250306082',
    projectId: 'okhealth-b8d73',
    authDomain: 'okhealth-b8d73.firebaseapp.com',
    databaseURL: 'https://okhealth-b8d73-default-rtdb.firebaseio.com',
    storageBucket: 'okhealth-b8d73.firebasestorage.app',
  );
}
